### ISSUE TITLE
Thermal Expansion Machines reset when leaving the dimension

### ISSUE THREAD

**Issue by Thicc-Daddyy** [xJon/The-1.7.10-Pack#1995]
Thermal expansion machines will randomly rest and lose all augments when leaving and returning to the dimension you have placed them in.

I am playing in single-player on the newest update.

**Comment by xJon** [comment]
This has been a reported issue before which some players said was resolved with a modpack reinstall.
Can you try that and report back?

**Comment by xJon** [comment]
Can you try to manually add [this mod](https://modrinth.com/mod/tileentity-reset-fix/version/1.0.1-noreq) and see whether the issue is resolved?

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested!)

**Comment by Calajese** [comment]
> Can you try to manually add [this mod](https://modrinth.com/mod/tileentity-reset-fix/version/1.0.1-noreq) and see whether the issue is resolved? Another recommended workaround is making sure your base stays chunkloaded.

I'm running a server and currently stumbling into this issue, tried adding the mentioned mod but no luck there. Checking the logs doesn't seem to reveal anything, though if wanted I can send them here. Re-extracting the server but using the same map the issue persists(Haven't tested if a new map works or not). Leaving a chunkloader around does work though.

**Comment by xJon** [comment]
@Calajese Thank you for your input. Unfortunately it seems the only current workaround is a chunk loader.
If you want to help and can reproduce the issue effectively, you can try to manually disable the ArchaicFix mod from both the server & client and let us know if the issue is still apparent.

**Comment by xJon** [comment]
Marking as duplicate due to https://github.com/xJon/The-1.7.10-Pack/issues/1984#issuecomment-1876233556.

**Comment by xJon** [comment]
Should be resolved in `0.10.12` :)
